# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: coderz

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Build app
        run: |
          npm install
          GENERATE_SOURCEMAP=false npm run build

      - name: Zip artifact for deployment
        run: |
          CURRENT_DATE=$(date +"%Y-%m-%d")
          ZIP_FILE="release_${CURRENT_DATE}.zip"
          zip -r "$ZIP_FILE" ./build


      - name: Download gdrive binary
        run: |
          wget -O gdrive.tar.gz https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_386.tar.gz
          tar -xzvf gdrive.tar.gz
          chmod +x gdrive
          sudo mv gdrive /usr/local/bin/gdrive
          sudo chown root:root /usr/local/bin/gdrive  # Change the owner to root

      - name: Make gdrive executable
        run: sudo chmod +x /usr/local/bin/gdrive

      - name: Authenticate with Google Drive
        env:
          GDRIVE_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_CREDENTIALS }}
        run: |
          echo "$GDRIVE_SERVICE_ACCOUNT_CREDENTIALS" > service_account.json
          mkdir -p /home/runner/.gdrive
          mv service_account.json /home/runner/.gdrive/
          gdrive --service-account service_account.json about
          LATEST_FILE=$(ls -t | head -n1)
          gdrive --service-account service_account.json upload --parent "1RE00_Lmg7DQ4A6yLjWJWv7NKMBJas000" "$ZIP_FILE"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download gdrive binary
        run: |
          wget -O gdrive.tar.gz https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_386.tar.gz
          tar -xzvf gdrive.tar.gz
          chmod +x gdrive
          sudo mv gdrive /usr/local/bin/gdrive
          sudo chown root:root /usr/local/bin/gdrive  # Change the owner to root
  
      - name: Authenticate with Google Drive
        env:
          GDRIVE_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_CREDENTIALS }}
        run: |
          echo "$GDRIVE_SERVICE_ACCOUNT_CREDENTIALS" > service_account.json
          mkdir -p /home/runner/.gdrive
          mv service_account.json /home/runner/.gdrive/
          gdrive --service-account service_account.json about
          gdrive --service-account service_account.json download --path . "1RE00_Lmg7DQ4A6yLjWJWv7NKMBJas000"
        

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm ./release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_05AF975F39B641D382B0AB9D4493572C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_611924CC35E94C4FB07A0E39924A9024 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7C3736AC60994FE1A4962CBB5931904D }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: coderz
          resource-group-name: tesla
          slot-name: 'Production'
          package: ./
